### ISSUE TITLE
Trying to use @azure/cosmos causes exception

### ISSUE THREAD

**Issue by vinnytheviking** [Azure/azure-cosmos-js#100]
Good morning,

As requested by @southpolesteve , I'm opening the issue here rather than the other repository.

I'm trying to access cosmosdb from a react/typescript application. I've imported the library and trying to just read a database. I'm using the v2 @azure/cosmos npm rather than documentdb npm. I was getting CORS issues with documentdb so trying to see if v2 fixes that.

These are the exceptions showing in the client.

ERROR in [at-loader] ./node_modules/@azure/cosmos/lib/queryIterator.d.ts:68:25
TS2304: Cannot find name 'AsyncIterable'.
ERROR in [at-loader] ./node_modules/@azure/cosmos/lib/request/request.d.ts:17:55
TS2694: Namespace '"url"' has no exported member 'UrlWithStringQuery'.
ERROR in [at-loader] ./node_modules/@azure/cosmos/lib/retry/retryUtility.d.ts:44:17
TS2694: Namespace '"url"' has no exported member 'UrlWithStringQuery'.
ERROR in [at-loader] ./node_modules/@azure/cosmos/lib/retry/sessionReadRetryPolicy.d.ts:32:70
TS2694: Namespace '"url"' has no exported member 'UrlWithStringQuery'.

Any ideas how I fix these.

**Comment by christopheranderson** [comment]
There will still be CORS issues with this new SDK, but we're working on addressing that on the service side.

These issues look like an issue with polyfils/etc. @southpolesteve will take a look and see if he has a work around.

You will still be blocked by CORS until we resolve the backend changes (which are in progress).

**Comment by southpolesteve** [comment]
@vinnytheviking Thanks for moving the issue over here. Which browser and version are you using? 

RE: CORS. As Chris said there will certainly still be an issue getting this working because the server side does not yet support CORS yet. However, it is possible to proxy the calls through your own server as a workaround.

**Comment by vinnytheviking** [comment]
Thank you for all the feedback.

I'm going down the api route rather than call cosmos directly from the UI layer. 

Much appreciated

**Comment by southpolesteve** [comment]
For anyone following this thread, this package currently only supports Typescript 3.0 and above. We're looking at ways to support older Typescript versions over in https://github.com/Azure/azure-cosmos-js/issues/205

CORS is also now officially supported. You can set allowed CORS domains in the Azure portal UI
