### ISSUE TITLE
Need samples/docs for alternative to hasMoreResults()

### ISSUE THREAD

**Issue by k-miyake** [Azure/azure-cosmos-js#105]
According to the API reference "hasMoreResults" is abolished. 
However, there is no sample of alternative, so it is difficult to understand how to change it. 
In addition, "hasMoreResults" is still used for many tests.

I think it would be nice to have samples on how to change the following code.

```js
while (queryIterator.hasMoreResults()) {
    let { result: items } = await queryIterator.executeNext();
    console.log(items);
}
```

**Comment by southpolesteve** [comment]
`hasMoreResults` is still on QueryIterator https://github.com/Azure/azure-cosmos-js/blob/5861d011adcc754d66b3391008eb25a88aab14b1/src/queryIterator.ts#L101
