### ISSUE TITLE
Add samples for getting and setting continuation token

### ISSUE THREAD

**Issue by emrekenci** [Azure/azure-cosmos-js#113]
```
        var query = "SELECT TOP 10 * FROM People"

        const querySpec = {
            query: query
        };

        var result = await container.items.query(querySpec).toArray();
```
How do I get the continuation token for the next 10 items from the result and how do I set it in the next query?

**Update**

The solution was provided [on this SO question](https://stackoverflow.com/questions/52149664/how-to-get-set-cosmos-db-continuation-token-in-javascript) by Jay Gong. We should add this to the sample file.

**Comment by christopheranderson** [comment]
executeNext in query.spec.ts now has this sample, resolving as part of issue clean up
