### ISSUE TITLE
Consistent Promise rejection objects

### ISSUE THREAD

**Issue by gluwer** [Azure/azure-cosmos-js#119]
Hi,

At the moment if there will be a communcation error (eg. ECONNREFUSED), it is the case, but if will be a 409 from the CosmosDB service or something similar rejection is a standard object. It would be nice to be consistent. In addition it is a good practice to have Error as a rejection reason.

**Comment by christopheranderson** [comment]
Agreed. We should properly wrap all these errors. I'll try to clean all these leaks up before GA.

**Comment by southpolesteve** [comment]
Errors in v3 are now proper Error objects and the message/code are set from whatever the backend returns. We still may add some additional errors of our own that extend `Error`, but for now, this is a good improvement over the v2 behavior. Closing.
