### ISSUE TITLE
Request clearer error message than "Error: invalid input: input is not string"

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cosmos-js#121]
`Error: invalid input: input is not string` seems to happen in a number of situations, an this error message on its own is not enough to determine what the problem is.

For example

```
  const document = { id: 'amazing', content: 'Hello Miss Amazing!' };
  const { body } = await container.items.upsert(document);
```

This works in one example and not in another ... it makes me think the doc content is invalid, but it's not clear if it means the values in the doc, the doc itself, the container ... or something else.

cc @christopheranderson

**Comment by johnpapa** [comment]
it may be related to when i connect with a db id vs a database object with an id property.

**Comment by christopheranderson** [comment]
Couldn't repro this in V3. Maybe related to partition key issues? Closing for now.

**Comment by fanyang-ceg** [comment]
I had exact same issue. the error was throw at trimSlashFromLeftAndRight (in @azure\cosmos\dist\index.js (438), somehow the input parameter containerId is an object, not a string.

**Comment by southpolesteve** [comment]
@fanyang-ceg Development of @azure/cosmos has moved to this repo: https://github.com/Azure/azure-sdk-for-js/issues

Can you file an issue there with a reproduction of the problem?

**Comment by fanyang-ceg** [comment]
Report the issue at [here](https://github.com/Azure/azure-sdk-for-js/issues/10911)
