### ISSUE TITLE
When Database or Container is not found, no error is thrown

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cosmos-js#123]
When i run 

```
  const container = await client
    .database(databaseDefName)
    .container(heroContainer);
```

and the database or container name is not found, I still get back a valid container object. Then when I run 

```
    const { result: heroes } = await container.items.readAll().toArray();
```

it throws an error with "resource does not exist"

I would expect that if the container or database name was not found that the first line of code would fail or alert me.

cc @christopheranderson

**Comment by christopheranderson** [comment]
That first line of code doesn't return a promise. Only methods that return promises will throw such errors. Unfortunately, it isn't a runtime error to await a non-promise, so it can be hard to catch these kinds of issues.

Gonna close this as "by-design", but I'll keep thinking about what we might be able to do. (I could do some hacky things with a Proxy object which catches "then" method calls and throws with a clear error, for instance, but I've never heard of anyone else doing something like that.)
