### ISSUE TITLE
Cannot find name 'AsyncIterable'

### ISSUE THREAD

**Issue by burkeholland** [Azure/azure-cosmos-js#127]
The following error is thrown

```
c:/dev/burkeholland/ignite-app/node_modules/@azure/cosmos/lib/queryIterator.d.ts(68,25): error TS2304: Cannot find name 'AsyncIterable'.
```

This is resolved by adding the following to `compilerOptions` in the tsconfig.json...

```
"lib": [
  "esnext"
]
```

Perhaps we can mention something in the docs about this? Or maybe I'm doing something else wrong?

**Comment by ealsur** [comment]
Thanks Burk! We'll get it fixed today.

**Comment by southpolesteve** [comment]
@burkeholland The linked PR should fix, but CI seems to be unhappy at the moment for unrelated reasons. Not ideal, but if you pull that branch and npm link you can try it out

**Comment by burkeholland** [comment]
Thanks, folks! That was fast 🏎

**Comment by martinmicunda** [comment]
@southpolesteve I have the same issue even when I added `esnext` to `tsconfig.json`:

cosmos version: `"@azure/cosmos": "2.0.2"`
nodejs: `v10.12.0`

```
"lib": [
  "esnext"
]
```
The `node_modules/@azure/cosmos/lib/queryIterator.d.ts:68:25 - error TS2304: Cannot find name 'AsyncIterable'.` error is only throw when I want build production build with `npm run build`

```json
 "scripts": {
    "build": "rm -rf dist && tsc",
    "dev": "nodemon --exec ts-node -- ./index.ts",
 }
```

**Comment by southpolesteve** [comment]
@martinmicunda can you try the latest version (2.0.4)?

**Comment by martinmicunda** [comment]
@southpolesteve 2.0.4 works thanks! ;)
