### ISSUE TITLE
Typescript Compile Error: resourceId.d.ts: BigInteger

### ISSUE THREAD

**Issue by bluto56** [Azure/azure-cosmos-js#145]
**Issue**

When compiling with 2.0.1 version of cosmos lib, the build fails with the following error

`> tsc --project tsconfig.json

node_modules/@azure/cosmos/lib/common/resourceId.d.ts:2:8 - error TS1192: Module '"/app/parking-storage-client/node_modules/big-integer/BigInteger"' has no default export.

2 import BigInt from "big-integer";`

**Expected Behavior**
Compilation works

**Reproduction steps**
When I use 2.0.0-4 compilation works. When I change to 2.0.1 it fails. With no other code issues changes.

** Versions **
    "ts-node": "^7.0.0",
    "tslint": "^5.10.0",
    "typescript": "2.9.2"

_tsconfig.json_
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "declaration": true,
    "noImplicitAny": false,
    "noEmitOnError": true,
    "noImplicitReturns": true,
    "noResolve": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "rootDir": "./",
    "outDir": "./out",
    "lib": [
      "es5",
      "es6",
      "dom",
      "es2015.core",
      "es2015.collection",
      "es2015.generator",
      "es2015.iterable",
      "es2015.promise",
      "es2015.proxy",
      "es2015.reflect",
      "es2015.symbol",
      "es2015.symbol.wellknown",
      "esnext.asynciterable"
    ]
  },
  "include": [
    "index.ts",
    "./src/**/*.ts",
    "./test/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "index.d.ts",
    "./src/**/*.d.ts",
    "./test/**/*.d.ts"
  ]
}
```

**Comment by christopheranderson** [comment]
This is another case of internal types leaking through, @southpolesteve. Maybe we need to publish a custom .d.ts which avoids that stuff? This looks like's its caused by our change to get rid of "import * as" stuff.

@bluto56 - does setting `"esModuleInterop": true ` fix the issue? If not, does `"allowSyntheticDefaultImports": true,` work?

**Comment by bluto56** [comment]
@christopheranderson yes, esModuleInterop fixes the issue. but for my code throws a bunch of other issue's i'd need to clean up.
"allowSyntheticDefaultImports": true fixes it with out any other compilation issues.

:+1:

**Comment by christopheranderson** [comment]
Cool, glad you're unblocked.

@southpolesteve - we need to see whether we need to actually force others to set this setting. I'm really inclined to believe we need a separate .d.ts file for external consumption.

**Comment by DanielRosenwasser** [comment]
Have you looked into the `.d.ts` rollup functionality in https://github.com/Microsoft/web-build-tools/wiki/API-Extractor?

**Comment by christopheranderson** [comment]
I haven't looked at that tool, but it might be worth looking into. I like the other features like alpha/beta on new APIs/etc.

**Comment by christopheranderson** [comment]
Would that mean we ship a custom built .d.ts file, rather than the one out of tsc build?

**Comment by southpolesteve** [comment]
@bluto56 Looks like you worked around, but we have removed big-integer entirely so this should no longer be an issue
