### ISSUE TITLE
WHERE clause by name yields 0 results

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cosmos-js#149]
The following code yields 0 results for the data below. However, if I change the WHERE clause to search by `id`, it yields the one  row, corectly. Is `name` a problem?
```
async function queryHeroes() {
  querySpec.query = 'SELECT h.id, h.name, h.description FROM heroes h WHERE h.name = @name';
  querySpec.parameters = [
    {
      name: '@name',
      value: 'Aslaug',
    },
  ];

    const { result: heroes } = await container.items.query(querySpec).toArray();
    heroes.forEach((queryResult) => {
      const resultString = JSON.stringify(queryResult);
    });
}
```

this works ...

```
  const querySpec = {
    query: 'SELECT h.id, h.name, h.description FROM heroes h WHERE h.id = @heroId',
    parameters: [
      {
        name: '@heroId',
        value: 'HeroAslaug',
      },
    ],
  };
```

the data is here

```
{
  "id": "HeroAslaug",
  "name": "Aslaug",
  "description": "warrior queen",
  "_rid": "cew3ANAWBRABAAAAAAAAAA==",
  "_self": "dbs/cew3AA==/colls/cew3ANAWBRA=/docs/cew3ANAWBRABAAAAAAAAAA==/",
  "_etag": "\"00006001-0000-0000-0000-5ba583c80000\"",
  "_attachments": "attachments/",
  "_ts": 1537573832
}
```

cc @christopheranderson

**Comment by johnpapa** [comment]
I had indexes turned off. i recreated the db and data with auto indexing turned on. 

is this why it didnt work before?

**Comment by christopheranderson** [comment]
Yeah, that's why it wasn't working. I was going to ask you to print out your container definition for me so I could see what your settings were. 👍 

Closing as resolved.

**Comment by johnpapa** [comment]
cool - the error was wacky. something about invalid string. the only field that worked was id, so i figured it must be an auto indexed field no matter what.

i agree on closing this ... but maybe a error message with some info about "check indexing " would help :)

BTW - this was very helpful. i found the link in the docs' tutorial https://www.documentdb.com/sql/demo

**Comment by christopheranderson** [comment]
Oh, there was an error message? I think we return an error if you don't search on any indexable fields. In general, we need to clean up some of the error messaging to be friendlier. 👍
