### ISSUE TITLE
Move samples to TypeScript

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmos-js#15]
Given that we have a great experience for development in TypeScript, I propose we move our existing samples to TypeScript.

We probably need 1 JS sample around. I propose we write a new one which does a little bit of everything.

**Comment by peterblazejewicz** [comment]
@christopheranderson 
this JS sample could have the @ts-check and doc directives in comments. I'm using that style at work, so when it's ready make a ref to me

**Comment by christopheranderson** [comment]
Definitely! I am actually adding //@ts-check to all the existing JS samples as I'm moving them to the new OM.

**Comment by southpolesteve** [comment]
Closed by #353
