### ISSUE TITLE
Cross partition query is required but disabled

### ISSUE THREAD

**Issue by donniekerr** [Azure/azure-cosmos-js#154]
How do I fix this in my query?
Cross partition query is required but disabled. Please set x-ms-documentdb-query-enablecrosspartition to true, specify x-ms-documentdb-partitionkey, or revise your query to avoid this exception

 `
const querySpec = {
        query: "SELECT * FROM c WHERE  c.documentId = @documentId",
        parameters: [
          {
            name: "@documentId",
            value: documentId
          }
        ]
      };
`

**Comment by donniekerr** [comment]
sorry, found the answer already.
 const { result: results } = await container.items
        .query(querySpec, { enableCrossPartitionQuery: true })
        .toArray(); 

Closing.

**Comment by aeroneer1** [comment]
This just helped me fix my problem, thanks!

**Comment by kennedykinyanjui** [comment]
Fix my problem. Thanks.

**Comment by pegasus1982** [comment]
Thanks @donniekerr

**Comment by dimon2255** [comment]
Fixes my problem, thanks.
