### ISSUE TITLE
[Question] Can I store ArrayBuffer / Buffer / binary data?

### ISSUE THREAD

**Issue by chadbr** [Azure/azure-cosmos-js#155]
Can I safely store Buffer's in Cosmos with the nodejs client?

for example - an object like this embedded in a document?

```javascript
let bufferOne = Buffer.from('This is a buffer example.');
console.log(bufferOne);

// Output: <Buffer 54 68 69 73 20 69 73 20 61 20 62 75 66 66 65 72 20 65 78 61 6d 70 6c 65 2e>

let json = JSON.stringify(bufferOne);
console.log(json);

// Output: {"type":"Buffer","data":[84,104,105,115,32,105,115,32,97,32,98,117,102,102,101,114,32,101,120,97,109,112,108,101,46]}
```

from: https://hackernoon.com/https-medium-com-amanhimself-converting-a-buffer-to-json-and-utf8-strings-in-nodejs-2150b1e3de57

---

We have large float arrays we'd like to store in a binary form (and pass to a web browser / WebGL, for example).

Thanks, Chad

**Comment by southpolesteve** [comment]
@chadbr Should be fine. JSON.stringify will get called on the object you save. You'll have to convert it to a buffer when you pull it back out. I've confirmed this code works:

```
const CosmosClient = require('@azure/cosmos').CosmosClient

const endpoint = "Your endpoint"
const masterKey = "Your master key"

const client = new CosmosClient({ endpoint, auth: { masterKey } });

const container = client.database("database").container("collection")

container.items.create({
  binaryData: Buffer.from('This is a buffer example.')
})
```

**Comment by chadbr** [comment]
thanks much @southpolesteve
