### ISSUE TITLE
MaxItemCount not being respected

### ISSUE THREAD

**Issue by dustensalinas** [Azure/azure-cosmos-js#157]
maxItemCount not being respected during query.  Sample below returns >1.

`
        let options = {
            enableCrossPartitionQuery: true,
            populateQueryMetrics: true,
            maxItemCount: 1 
        }

        let querySpec =
        {
            query: "SELECT C.id, C.company_name FROM Customers C"
        };
        let response = await this.container.items.query(querySpec, options).toArray();
`

**Comment by southpolesteve** [comment]
@dustensalinas `maxItemCount` is a bit confusing. It only applies to the number of items retrieved in each round trip to the server. By calling `toArray()` you are telling the SDK to exhaustively execute the query. With `maxItemCount` = 1 and a collection with two items it ends up doing two requests to the server each returning 1 item. Those are then combined into the response. If you want results of just a single round trip, try using `query().current()` or `query.getAsyncIterator()`. The latter will allow you to do something like:

```
for await(const {result } in this.container.query(querySpec).getAsyncIterator()) {
	console.log(result.length);
}
```

Depending on your use case you might also use the `TOP` statement inside your SQL query https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query#TopKeyword

Here is a full example for using `current` and showing how maxItemCount results in multiple round trips:

``` js
const client = new CosmosClient({ endpoint, auth: { masterKey } });

const container = client.database("database").container("collection")

let options = {
  enableCrossPartitionQuery: true,
  populateQueryMetrics: true,
  maxItemCount: 1
}
  
let querySpec = {
  query: "SELECT * FROM c"
};

async function main (){
  let response = await container.items.query(querySpec, options)
  let current = await response.current()
  let next = await response.executeNext()
  console.log(current.result.length) // 1
  console.log(next.result.length) // 1
}

main()
```
