### ISSUE TITLE
Add production dependency on @types/node

### ISSUE THREAD

**Issue by southpolesteve** [Azure/azure-cosmos-js#160]
Typescript users of this library need to install @types/node. Guidance from Typescript docs say we should include it in dependencies: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Upside: 
- Better out of the box experience for TS users

Downside: 
- Our version of node types could conflict with a user's version?
- Non-TS users download unnecessary packages

**Comment by christopheranderson** [comment]
Another alternative to weigh here to to get rid of these types all together. I think we're doing this just for the `Agent` type. I wonder if we could just create an interface for that type and remove the dependency all together.

**Comment by christopheranderson** [comment]
Overall, though, I don't have a problem with the downsides except some worry about the version conflicts, which are always annoying. We'll want to target the lowest LTS we support.

**Comment by southpolesteve** [comment]
Closed by https://github.com/Azure/azure-cosmos-js/pull/175. We no longer expose types from @types/node
