### ISSUE TITLE
Attachments property is missing from Container

### ISSUE THREAD

**Issue by ctstone** [Azure/azure-cosmos-js#177]
I would expect to find `.attachment(id: string)` and `.attachments` properties on a `Container` instance, but there are none.

Is there another way to upload media to a document? Or is attachment support coming soon?

**Comment by christopheranderson** [comment]
We are evaluating the future of the Attachments feature. Attachments feature today is still in preview, and has a number of limitations, e.g. it does not compose with other service capabilities like global distribution.

For small binary payload, we recommend making it part of the Item.

For large binary payload, we recommend storing it in Azure storage and referencing it from Cosmos DB.

**Comment by ctstone** [comment]
Thanks for the info. I went with blob storage, which has other nice features like SAS URL.

**Comment by christopheranderson** [comment]
Closing and locking this. Open a new issue if you have similar questions.
