### ISSUE TITLE
Reference error when compiling .ts Typescript files

### ISSUE THREAD

**Issue by pconnell99** [Azure/azure-cosmos-js#182]
When trying to use the library in a Typescript project, `tsc -w` throws the following error:-

```
node_modules/@azure/cosmos/lib/queryIterator.d.ts:1:1 - error TS1084: Invalid 'reference' directive syntax.

1 /// <reference lib="esnext.asynciterable" />

```

Removing this line from the file allows compilation.  I did add `--skipLibCheck` but this did not work.

Am I doing it wrong?

tsc --version = 2.9.2

**Comment by southpolesteve** [comment]
@pconnell99 are you able to use the latest version of typescript?

**Comment by pconnell99** [comment]
Sorry, just realise there's an update - can't keep track of which library/tool has updated when - whatever happened to stability!  Upgraded to 3.1.6 (somehow) and it compiled.  Will close.

**Comment by southpolesteve** [comment]
No worries! Glad to hear upgrading resolved it. We're aware that a recent change broke compatibility with Typescript v2 but we are hoping that upgrading to v3 will be an option for users.
