### ISSUE TITLE
Single partition queries return "current" value for "next" calls.

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmos-js#185]
If you have a single partition query which uses the DefaultExecutionContext, "next" returns "current".

So code like
```typescript
const {result: curr} = await iterator.current();
const {result: next} = await iterator.next();
assert.equal(curr, next);
```

Would succeed, when it shouldn't.

**Comment by southpolesteve** [comment]
@christopheranderson I believe this was fixed in #187. If not, please reopen
