### ISSUE TITLE
Ability to cancel on QueryIterator

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-cosmos-js#193]
Is there any possibility of canceling further parts of a query through the QueryIterator?

**Comment by christopheranderson** [comment]
This is something I'd like to do. I was thinking of doing a simple solution like:

```typescript
interface CancelationToken {
    shouldCancel: boolean;
}
```

And then making that an option on `FeedOptions` and `RequestOptions`. 

Then you could do something like:

```
const cancel = { shouldCancel: false };
setTimeout(()=>{cancel.shouldCancel = true}, 10000);
const {result} = await items.query("select value count()", { enableCrossPartition: true, cancelToken: cancel }).toArray();
```

When it is canceled early, we'd throw an error that indicated we got a signal to cancel. It would cancel when it attempted the next request, so it won't be instant that it cancels, it, but it will cancel next change it gets. All the other options I have in mind involve breaking-ish changes.

There are some other options out there on how to do Promise cancelation in JavaScript. [Ben's blog post is my favorite summary](https://medium.com/@benlesh/promise-cancellation-is-dead-long-live-promise-cancellation-c6601f1f5082).

I like moving to Rx at some point as a solution, tbh, but that's a pretty big leap.

Thoughts? Good feature for some feedback on what the ideal experience would be here.

**Comment by southpolesteve** [comment]
I'll take this on in v3 as part of moving the internals to fetch. AbortController will allow us to expose this functionality https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort
