### ISSUE TITLE
Retry 503s for idempotent calls

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmos-js#20]
We can be a bit more aggressive on retries for 503s for idempotent operations.

Notes:

1)	We should simplify and standardize error handling irrespective of connection mode and SDK language. With that we should not be exposing E_CONN* to customers.
2)	PUT/DELETE are not idempotent operation.
3)	Upsert without ETAG is idempotent operation.
4)	All read operations are idempotent.
5)	500 – We should not recommend retry. Most likely it is not retriable error. We should also ensure we don’t return 500 for transient issue, instead should use 408/503 across the stack.

![image](https://user-images.githubusercontent.com/2252976/41792969-7c28aef6-760f-11e8-8e0e-a8354ce18b51.png)

**Comment by southpolesteve** [comment]
Closed as stale. Can revisit later
