### ISSUE TITLE
404 shouldn't throw for reads

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmos-js#203]
Throwing on 404s for reads is a little aggressive compared to other DB SDKs. We should consider returning undefined instead and not throwing.

This is a breaking change.

**Comment by mikhailshilkov** [comment]
+1
I query the container based on ID received from a user, so I *expect* a document might not be found. Having a try..catch around it seems ugly, especially since you already return a wrapper object `ItemResponse<ItemDefinition>`.
