### ISSUE TITLE
Trying to use @azure/cosmos in SPFx

### ISSUE THREAD

**Issue by AntyfrizZz** [Azure/azure-cosmos-js#205]
Hello everyone,

I am developing SPFx solution with react 16.3.2 and SPFx 1.7.0.
The compiler uses Typescript 2.4.2 due to dependencies on some libraries (if you need more info on them, i will post it).
After i installed @azure/cosmos 2.1.1, I have this error on building the project

`node_modules/@azure/cosmos/lib/src/ChangeFeedIterator.d.ts(1,1): error TS1084: Invalid 'reference' directive syntax.` - **`The line here is /// <reference lib="esnext.asynciterable" />`**
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,56): error TS1110: Type expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,63): error TS1138: Parameter declaration expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,84): error TS1005: ';' expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,85): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,100): error TS1139: Type parameter declaration expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,107): error TS1138: Parameter declaration expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,128): error TS1005: ';' expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,129): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,147): error TS1005: '=' expected.`
`node_modules/@azure/cosmos/lib/src/client/Container/Container.d.ts(121,148): error TS1109: Expression expected.` - **`All lines till here are related with that row of code - readPartitionKeyRanges(feedOptions?: FeedOptions): import("../../queryIterator").QueryIterator<import("./PartitionKeyRange").PartitionKeyRange>;`**
`node_modules/@azure/cosmos/lib/src/queryIterator.d.ts(1,1): error TS1084: Invalid 'reference' directive syntax.` - **`The line here is /// <reference lib="esnext.asynciterable" />`**

Best regards,
Yavor

**Comment by pgonzal** [comment]
@patmill FYI

**Comment by christopheranderson** [comment]
@southpolesteve - another case of asynciterator stuff biting us

@AntyfrizZz - can you share your tsconfig?

**Comment by southpolesteve** [comment]
@AntyfrizZz Unfortunately we are using syntax in our files .d.ts that is not supported in typescript <3.0. I'm brainstorming with the team to come up with a good solution. Please share your tsconfig when you can and I'll try and find a workaround.

**Comment by despian** [comment]
Just tried to install this an angular app using typescript 2.9.2 and coming across the same issue.

**Comment by southpolesteve** [comment]
@despian thanks for the details. We're aware this is is still an issue for users compiling for typescript <3.0. Can you open a new issue for any issues you are facing running it in the browser? Browser usage is big priority for us in the upcoming 3.0 branch.

**Comment by despian** [comment]
@southpolesteve as far as I remember the errors were related to some missing globals which are available in node but not in the browser, `process` and some others I think. The errors were thrown by one of this library's dependencies, I think it was tunnel.js and/or cipher-base.

Sorry, I don't really have time to look into this again and raise an issue. This is no longer a problem for me since I decided against running it in the browser.

**Comment by southpolesteve** [comment]
@despian Got it. If you do decide to use it in the browser you'll need to mock out some of the nodejs builtins like we do here: https://github.com/Azure/azure-cosmos-js/blob/master/webpack.config.js#L7-L9 This is something we are looking to make work out of the box in the next major version.

**Comment by sayinala** [comment]
@southpolesteve when is the V3 planned and does it resolve the issue of compilation for typescript <3.0?

**Comment by patmill** [comment]
Just as a heads up, with SPFx 1.8.2, you can use up to TS3.3 I believe.

**Comment by southpolesteve** [comment]
@patmill great news! 🙌

@sayinala Are you able to use 1.8.2 or greater?

**Comment by christopheranderson** [comment]
This is resolved now in the latest SPFx where you can now customize your TS version.
