### ISSUE TITLE
Readme: "Quick start" link 404's

### ISSUE THREAD

**Issue by mscoutermarsh** [Azure/azure-cosmos-js#214]
:wave:

The quick start link in the README currently 404's.

The link is `https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-nodejs-get-started-preview`

**Comment by southpolesteve** [comment]
@mscoutermarsh Is this on master? I'm seeing the correct link there https://github.com/Azure/azure-cosmos-js/blame/master/README.md#L43

**Comment by mscoutermarsh** [comment]
Works now! closing 😄
