### ISSUE TITLE
Offer experience

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmos-js#22]
A couple of issues on offer experience:

 - Offer is RID based, which means it doesn't fit into our name based OM very cleanly
 - To update an offer, you need to pass it the RID of a resource (you cannot use named based links)
    - This means even if we put it under container/database, we would still have to shim the call with a read container/database call to grab the RID before we could update the offer for it.

It's currently disabled in the new OM, but it's required for updating an existing container/database.

**Comment by southpolesteve** [comment]
Works for create already in v3. But not update. Needs port to v2
