### ISSUE TITLE
Trying to query documents results in a Parse Error: HPE_HEADER_OVERFLOW

### ISSUE THREAD

**Issue by petmat** [Azure/azure-cosmos-js#221]
I am using the @azure/cosmos NPM package to query documents from CosmosDB and it results in the following error:

```
{ Error: Parse Error
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
  bytesParsed: 0,
  code: 'HPE_HEADER_OVERFLOW',
  headers:
   { 'x-ms-throttle-retry-count': 1,
     'x-ms-throttle-retry-wait-time-ms': 4059 } }
```

@azure/cosmos@2.1.1
Node.js 10.15.0

I'm using the following code:

```
const cosmos = require('@azure/cosmos');
const config = require('./local.settings.json');

const { CosmosClient } = cosmos;

const { endpoint, key } = config;
console.log(endpoint, key);
const client = new CosmosClient({ endpoint, auth: { key } });

const dbId = 'DB';
const containerId = 'Items';

async function getChats() {
  const querySpec =
    'SELECT * FROM c WHERE c.type = "ChatDefinition" AND c.roomId = "062db3be-339e-11e6-bebb-00163e75537f" AND c.lastEntry >= "2019-01-01"';
  const { result } = await client
    .database(dbId)
    .container(containerId)
    .items.query(querySpec)
    .toArray();
  return result;
}

async function run() {
  console.log('Gettings chats...');
  const chats = await getChats();
  console.log(chats.length);
}

run().catch(console.error);
```

**Comment by southpolesteve** [comment]
@petmat One more Q. Roughly how much data is in this collection and what is the partition key? Feel free to email me if you don't want to disclose here: stfaul@microsoft.com

**Comment by rafa98765** [comment]
I have the same problem, the functio call to cosmos api and return

    "message": "Error en function{\"bytesParsed\":16383,\"code\":\"HPE_HEADER_OVERFLOW\",\"headers\":{\"x-ms-throttle-retry-count\":0,\"x-ms-throttle-retry-wait-time-ms\":0}}"

**Comment by southpolesteve** [comment]
@rafa98765 Could you try on node 10.14.10 and see if the error still exists? I've not been able to reproduce the error yet or confirm it is related to the upstream change that nodejs made

**Comment by rafa98765** [comment]
Yes, the error is in 10.14.1 version of node. But only when I get values for 2 cosmos db. And we made a migration between 2 cosmos, with datafactory v2, it is relevant?

**Comment by bertschneider** [comment]
FYI: We got around this issue adding the `--max-http-header-size` node flag.

**Comment by bialad** [comment]
I've also encountered this error while querying with a result of just 150 values+timestamp.

I don't understand how such a small payload can overload the header limit. I'm using cosmos db as a IoT telemetry storage, where I'm expecting to query for thousands of data points at a time, which doesn't seem to be what it's made for with this limit.

**Comment by southpolesteve** [comment]
@bialad Can you provide a sample query or some data? I'd really like to figure out this problem but I've had trouble replicating this issue. My email is a few comments above if that is preferable.

**Comment by bialad** [comment]
This is the error I get:
```
{ Error: Parse Error
    at TLSSocket.socketOnData (_http_client.js:447:20)
    at TLSSocket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:150:17)
  bytesParsed: 16383,
  code: 'HPE_HEADER_OVERFLOW',
  headers:
   { 'x-ms-throttle-retry-count': 0,
     'x-ms-throttle-retry-wait-time-ms': 0 } }
(node:30605) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `result` of 'undefined' or 'null'.
    at Object.queryContainer (/data/projects/tobias/cloud-iot-test/azure/website/data-api/db.service.js:27:31)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:30605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```
This is the query being sent:
```
  const querySpec = {
    query: `SELECT TOP 150 c["value"], c["sourcetimestamp"]
              FROM opc c 
              WHERE c.nodeid = @nodeid AND c.sourcetimestamp > @from
              ORDER BY c.sourcetimestamp DESC`,
    parameters: [
      {
        name: "@nodeid",
        value: req.body.nodeid
      },
      {
        name: "@from",
        value: req.body.from
      }
    ]
  };
```
This is the response of the same query with TOP 10 (which works):
```
[{"value":25,"sourcetimestamp":"2019-04-05T09:32:09.95375Z"},{"value":27,"sourcetimestamp":"2019-04-05T09:31:59.95375Z"},{"value":30,"sourcetimestamp":"2019-04-05T09:31:49.95375Z"},{"value":32,"sourcetimestamp":"2019-04-05T09:31:39.95375Z"},{"value":38,"sourcetimestamp":"2019-04-05T09:31:29.95375Z"}]
```

**Comment by tony-gutierrez** [comment]
Same problem with pretty small query in node 10.14.1

**Comment by tony-gutierrez** [comment]
Verified that this issue was caused by the newer version of cosmosdb that has the database wide dtu limit. The older version with collection dtu only works fine.

**Comment by tony-gutierrez** [comment]
Be advised that Azure App Service does not support any node version with the "--max-http-header-size" flag. So your DB is now useless on your own app service.

**Comment by tony-gutierrez** [comment]
For those wondering, node 10.13.0 is before the introduced 8kb limit.

**Comment by m4recek** [comment]
Hi, did this moved somewhere?

We have replicated the issue on Node 8.15.0 for fairly trivial queries. We are not able to set `--max-http-header-size` since we are running in a cloud environment not managed by us.

**Comment by tony-gutierrez** [comment]
Yeah, this basically means if you are using the azure sdk, you are locked to older node.

**Comment by southpolesteve** [comment]
@christopheranderson can you tag the app service people so they are aware of this on their side?

**Comment by tony-gutierrez** [comment]
Node 10.15.2 is not available on app service. You should be able to somehow execute it with the --max-http-header-size=81000 flag, however I have yet to figure out how.

**Comment by christopheranderson** [comment]
I just emailed the App Service team to ask them how to do that and if they can potentially do it automatically.

**Comment by tony-gutierrez** [comment]
Adding
```
nodeProcessCommandLine: "D:\Program Files (x86)\nodejs\10.15.2\node.exe"
```
to iisnode.yml works, but adding 
```
nodeProcessCommandLine: "D:\Program Files (x86)\nodejs\10.15.2\node.exe --max-http-header-size=81000"
```

does not.

**Comment by tony-gutierrez** [comment]
Eliminating the quotes works, as described here. 

So by creating iisnode.yml in root, adding `nodeProcessCommandLine: D:\Program Files (x86)\nodejs\10.15.2\node.exe --max-http-header-size=81000` you should be able to avoid the header problem and continue to use newer node versions. You can verify by doing a `console.log(http.maxHeaderSize)`;

Also it is posible that a smaller value than 81000 will also work.

It would be nice if the cosmos node sdk could work inside of the 8k header bounds that are not the default in node, but I am sure that is easier said then done.

**Comment by rramachand21** [comment]
https://github.com/tjanczuk/iisnode/issues/315

**Comment by leo-buneev** [comment]
For the record (I'm constructing REST queries manually, not using this SDK) - if setting "--max-http-header-size" is not possible for you, you can send additional header , `x-ms-documentdb-responsecontinuationtokenlimitinkb`, that will force cosmosdb server to not send too much information in cont. token. For example:
```
headers['x-ms-documentdb-responsecontinuationtokenlimitinkb'] = '7'
```
The downside is - RU usage for getting subsequent pages may increase (because there's less info in cont. token to help cosmosDb retrieve data efficiently)

**Comment by southpolesteve** [comment]
I've chatted with the backend team and determined we can safely default the header to 1kb. I've done this in #384 and exposed the option to make it larger. This should help significantly with header limit issues. It is still possible for collections with VERY large numbers of partitions to have a large session token, but continuation token is the main culprit.
