### ISSUE TITLE
Expose the continuation token as a property on responses

### ISSUE THREAD

**Issue by connor4312** [Azure/azure-cosmos-js#229]
It'd be quite helpful to expose the continuation token as a typed property of item responses. Eventually I found this [SO question](https://stackoverflow.com/questions/52149664/how-to-get-set-cosmos-db-continuation-token-in-javascript) which describes how to retrieve the continuation token, but this isn't documented anywhere (at least nowhere specific to Node.js usage of Cosmos DB that I was able to find online) and exposing the token as its own property would allow IntelliSense/autocomplete to show developers where to find it in their editors, avoiding context switching and making the development process faster.

Related: https://github.com/Azure/azure-cosmos-js/issues/113 https://github.com/Azure/azure-cosmos-js/issues/75

**Comment by southpolesteve** [comment]
@connor4312 Thanks for the suggestion. Redoing the response objects for version 3 is on our list and we'll def incorporate this.

**Comment by christopheranderson** [comment]
This is done for V3.
