### ISSUE TITLE
Azure Cosmos DB Node.js Samples are missing upsert sample

### ISSUE THREAD

**Issue by petmat** [Azure/azure-cosmos-js#231]
The samples here https://github.com/Azure/azure-cosmos-js/blob/216672a679ab389e5b341280eeacab1cab3691e4/samples/ItemManagement/app.js are listed from 1 to 7 and number 6 is supposed to be: 6. upsert item    - Update a item if it exists, else create new item. However if you look at the actual code, number 6 is delete item and the upsert item sample is missing completely.

Can you update the samples to include the upsert sample?

**Comment by ShaguftasayaniEY** [comment]
any updates on this? @petmat @christopheranderson @jdhuntington @chad @Zariel

**Comment by southpolesteve** [comment]
This should exit now. Added in #136 

https://github.com/Azure/azure-cosmos-js/blob/master/samples/ItemManagement/app.js#L156-L172
