### ISSUE TITLE
Incorrect SqlParameter type

### ISSUE THREAD

**Issue by princjef** [Azure/azure-cosmos-js#233]
The `SqlParameter` type restricts the `value` property to `string | number | boolean`:

https://github.com/Azure/azure-cosmos-js/blob/fbe56ef09f12111381bf7701ffcb4004cea7dad6/src/queryExecutionContext/SqlQuerySpec.ts#L23-L31

However, according to the [docs](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-sql-query#parameterized-sql-queries):

> Parameter values can be any valid JSON (strings, numbers, Booleans, null, even arrays or nested JSON). Also since Cosmos DB is schema-less, parameters are not validated against any type.

I have also observed that if I bypass Typescript's type check, array and object types are accepted at runtime by the database. Therefore, it seems like the type needs to be updated.

The most correct type for the `value` property would probably be the `JSONValue` type as defined below:

```ts
export type JSONValue = string | number | boolean | null | JSONObject | JSONArray;

export interface JSONObject {
    [x: string]: JSONValue;
}

export interface JSONArray extends Array<JSONValue> { }
```

That said, I think that it would also be fine to mark the type as either `any` or a looser form of the `JSONValue` type defined as such:

```ts
export type JSONValue = string | number | boolean | null | object | any[];
```

Environment:
 * Node.js version: 8.14.0
 * `@azure/cosmos` version: 2.1.1

**Comment by christopheranderson** [comment]
This is a really well thought out issue. Thank you for that.

I'll see if your types work, if I need any adjustments, and add some better test coverage here for acceptable queries to make sure they'll definitely work.
