### ISSUE TITLE
Single cosmosClient VS dedicated clients per query

### ISSUE THREAD

**Issue by johanschram** [Azure/azure-cosmos-js#239]
Hi, 

I my nodeJS code, I set up a new CosmosClient on app launch, and this single client is reused for each querie.

Eventually, I notice that when something goes wrong with a query (in my case queries that overpass a collection throughput), all new queries (on any other collections) take much more time to execute.

So, I was wondering if reusing the same cosmoClient all over is a good idea. Wouldn't it be a better idea to  create a new client for each incomming query and somehow destroy the client after the query is done ? As I do not fully undestand what's behind, this might be a stupid question, but well, it worths asking ! 

Thank you in advance for any thoughts about this. 

@azure/cosmos@2.0.5
Node.js 8.12.0

**Comment by southpolesteve** [comment]
@johanschram Reusing the created `CosmosClient` is correct. Recreating client is not ideal. It will, by default, do an endpoint discovery call the first time it is used which will add an unnecessary call as part of every query.

So, sound like a bug. Can you share some code that reproduces the issue? If you want to keep any code private, feel free to email me: stfaul@microsoft.com

**Comment by christopheranderson** [comment]
Open a new issue if there is any further questions.
