### ISSUE TITLE
Remove client.partitionResolver

### ISSUE THREAD

**Issue by southpolesteve** [Azure/azure-cosmos-js#24]
The current client has the ability to set a custom partition resolver functions at `client.partitionResolver` usually with an instance of `HashPartitionResolver`. We should investigate:
- What use cases need this functionality 
- Are any existing users are relying on it
- How would we expose this in the new Object Model

**Comment by southpolesteve** [comment]
Temporarily commented out in d66b6dad9bebf6ad754c4504f04247bd9d21267e

**Comment by christopheranderson** [comment]
ping @kirillg for comment

**Comment by southpolesteve** [comment]
Changing this to a task to remove client.partitionResolver entirely. Not needed in new SDK

**Comment by southpolesteve** [comment]
It appears we never exposed this on `CosmosClient` so while all the internal code remains, there is no way for consumers to use it. Should be possible to delete all `partitionResolver` code after 2.0 RC without a breaking change.

**Comment by christopheranderson** [comment]
This was all deleted in the great purge of DocumentClient. Rejoice! 🔥✨🎂🎉
