### ISSUE TITLE
Incorrect type for Resource._ts

### ISSUE THREAD

**Issue by princjef** [Azure/azure-cosmos-js#251]
When working with resources using the `@azure/cosmos` package, a `Resource` type is returned with most APIs, which contains the common base schema. This works well, but the `_ts` property in the `Resource` type is defined as a `string`, rather than a `number`:

https://github.com/Azure/azure-cosmos-js/blob/ae53dbaaa996dbd56ba0e1b55bb95dfd7b4b510d/src/client/Resource.ts#L1-L13

From the actual data returned, as well as the [REST API examples](https://docs.microsoft.com/en-us/rest/api/cosmos-db/get-a-document#body-1), it seems like this type should be a number instead of a string.

Environment:

 - Node.js version: 8.14.0
 - @azure/cosmos version: 2.1.1

**Comment by southpolesteve** [comment]
Published in @azure/cosmos@2.1.3
