### ISSUE TITLE
can't read without partition key

### ISSUE THREAD

**Issue by mybouhssina** [Azure/azure-cosmos-js#254]
Hi, in all the docs reading is done like : 
const { body } = await this.container.item(someId).read();
but when I try this, I get the following error : 

>    '{"code":"BadRequest","message":"Message: {\\"Errors\\":[\\"**The partition key supplied
> in x-ms-partitionkey header has fewer components than defined in the the collection**.\\"]}\\r\\nActivityId: 4501f9b6-6cf0-4302-af8a-3f0c301a6e40, Request URI: /apps/b17af4e4-5a2b-4102-b120-24fea51d26be/services/6fe3b6a5-779a-42de-b533-686d091861a0/partitions/6d2e308c-600f-47b0-a486-6e109dd6c3ab/replicas/131965531264951348s, RequestStats: \\r\\nRequestStartTime: 2019-03-08T23:49:06.5071377Z, RequestEndTime: 2019-03-08T23:49:06.5071377Z, Number of regions attempted: 1\\r\\nResponseTime: 2019-03-08T23:49:06.5071377Z, StoreResult: StorePhysicalAddress: rntbd://10.0.0.49:16700/apps/b17af4e4-5a2b-4102-b120-24fea51d26be/services/6fe3b6a5-779a-42de-b533-686d091861a0/partitions/6d2e308c-600f-47b0-a486-6e109dd6c3ab/replicas/131965531264951348s, LSN: 5, GlobalCommittedLsn: 4, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 1001, RequestCharge: 0, ItemLSN: -1, SessionToken: -1#5, UsingLocalLSN: True, TransportException: null, ResourceType: Document, OperationType: Read\\r\\n, SDK: Microsoft.Azure.Documents.Common/2.2.0.0"}',

am I missing something ?

**Comment by southpolesteve** [comment]
@mybouhssina There are two way to pass the partition key value. Either the second argument to `item` or in the options of whatever method you are calling. It is required for partitioned containers:

```
  const item = await container.item('yourId', 'yourPartitionKeyValue')

  const item = await container
    .item('yourId')
    .read({ partitionKey: 'yourPartitionKeyValue' })
```

We do realize this is a bit confusing and needs better examples. We're planning to address it in the next major release.
