### ISSUE TITLE
typo on documentation

### ISSUE THREAD

**Issue by nickplennox** [Azure/azure-cosmos-js#256]
I found that this line

`  const { container } = await db.containers.create(collectionDefinition);`

needs to be: 

`  const { container } = await db.database.containers.create(collectionDefinition);`

**Comment by christopheranderson** [comment]
Where in the docs did you find this?

**Comment by nickplennox** [comment]
Hi, it's in README.MD.

Maybe the object model changed at some point?

**Comment by christopheranderson** [comment]
That readme sample runs fine for me when I copy paste it. In that sample `db` is of type `Database`. Your code would only make sense if db of was type `Container` accidentally.

Screencap of sample running on Node version 10.15.3:
![image](https://user-images.githubusercontent.com/2252976/54380638-31964780-4649-11e9-8e09-4f0da8b66a8d.png)

```javascript
//@ts-check
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0

const cosmos = require("@azure/cosmos");
const CosmosClient = cosmos.CosmosClient;

const endpoint = "https://localhost:8081"; // Add your endpoint
const masterKey = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="; // Add the masterkey of the endpoint
const client = new CosmosClient({ endpoint, auth: { masterKey } });

const databaseDefinition = { id: "sample database" };
const collectionDefinition = { id: "sample collection" };
const documentDefinition = { id: "hello world doc", content: "Hello World!" };

async function helloCosmos() {
  const { database: db } = await client.databases.create(databaseDefinition);
  console.log("created db");

  const { container } = await db.containers.create(collectionDefinition);
  console.log("created collection");

  const { body } = await container.items.create(documentDefinition);
  console.log("Created item with content: ", body.content);

  await db.delete();
  console.log("Deleted database");
}

helloCosmos().catch(err => {
  console.error(err);
});
```

**Comment by nickplennox** [comment]
Hi, I can see now the difference between my code and yours and this explains why I need to explicitly call `db.databases.containers.createIfNotExists`, while you do not.

Apologies, sorry to waste your time...
