### ISSUE TITLE
Replace hash based indexing samples with range based

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmos-js#260]
Lazy indexing example you can remove
https://github.com/Azure/azure-cosmos-js/blob/216672a679ab389e5b341280eeacab1cab3691e4/samples/IndexManagement/app.js#L183-L214

This is about a hash index on a string which can be deleted completely since we have the range on strings below it
https://github.com/Azure/azure-cosmos-js/blob/216672a679ab389e5b341280eeacab1cab3691e4/samples/IndexManagement/app.js#L219

need to change the comment here since range on strings is now default.
https://github.com/Azure/azure-cosmos-js/blob/216672a679ab389e5b341280eeacab1cab3691e4/samples/IndexManagement/app.js#L281

Remove “lazy”
https://github.com/Azure/azure-cosmos-js/blob/216672a679ab389e5b341280eeacab1cab3691e4/samples/IndexManagement/app.js#L281

In fact, there are ton’s of places where the sample and text is wrong. I would just sweep out anything where a query will fail because it has a hash index. Keep anything showing Range index but update text to reflect it’s the default now.

**Comment by southpolesteve** [comment]
Closed by #353
