### ISSUE TITLE
Stored Procedures in Typescript

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-cosmos-js#269]
Hello folks!

With the 2.0 SDK released, is there any plans to officially support TypeScript on CosmosDB for Stored Procedures (i.e. Server-side code)?

Azure Functions now support TypeScript as well so it would be good to support TS directly on CosmosDB. 

If that is not under the radar, is there any plans to at least release a TS definition file so we can code in TS then transpile to JS before publishing the procedures? 

Today we do that relying on `.d.ts` provided from someone on the community but I bet it is not fully updated (for example there is no `__` support) and would be nice to have an official solution for that.

PS: This is not valid anymore https://azure.github.io/azure-documentdb-js-server/

Thank you!

**Comment by southpolesteve** [comment]
@galvesribeiro thanks for the issue! I'm not sure if there are plans for first class support for TypeScript on the server side but the best place to raise that issue is here: https://github.com/Azure/azure-cosmosdb-js-server. This repo is just for client-side JS.
