### ISSUE TITLE
Enable default keepAlive on v3

### ISSUE THREAD

**Issue by southpolesteve** [Azure/azure-cosmos-js#281]
On v3 we no longer have a custom default agent IE https://github.com/Azure/azure-cosmos-js/pull/278. But we should figure out some way of having keepAlive on by default combined with fetch.

**Comment by tony-gutierrez** [comment]
If you aren't going to have a custom agent, I would think it would be sufficient to just note in the documentation that the default node agent, or the agent provided should be using keep alive for max perf.

**Comment by southpolesteve** [comment]
A quick write test showed that keepAlive is about 2x faster. Definitely going to have this as part of v3.
