### ISSUE TITLE
What is the best way to get the status code of a response?

### ISSUE THREAD

**Issue by talam** [Azure/azure-cosmos-js#312]
What is the best way to get the status code for a request to something like `StoredProcedure.execute`? `CosmosResponse` doesn't provide the `statusCode` field but it would be nice to have it available.

**Comment by southpolesteve** [comment]
@talam This is a known issue with the current major release. We've already fixed it on our soon to be previewed v3 branch. V3 should GA this quarter.

**Comment by talam** [comment]
Thanks. Closing the issue as it'll be resolved in v3.
