### ISSUE TITLE
Should useMultipleWriteLocations by true by default?

### ISSUE THREAD

**Issue by southpolesteve** [Azure/azure-cosmos-js#321]
Right now it is false. You can force the client to a specific endpoint by appending the region and skipping endpoint discovery:

```
const client = new CosmosClient({
  endpoint: "https://my-db-koreasouth.cosmos.azure.com",
  key,
  connectionPolicy: {
    enableEndpointDiscovery: false
  }
});
```

But writes will not work. You will get an "Operation forbidden in this region" error unless you set "useMultipleWriteLocations" to true in the connection policy

**Comment by christopheranderson** [comment]
Need to ask Pankaj and Ji. @christopheranderson do that.

**Comment by southpolesteve** [comment]
Closed by https://github.com/Azure/azure-cosmos-js/pull/335
