### ISSUE TITLE
Getting self signed certificate error with local cosmos db emulator

### ISSUE THREAD

**Issue by arulselvam** [Azure/azure-cosmos-js#386]
Even if I set `connectionPolicy.disableSSLVerification = true`, am getting self signed certificate error with local cosmos db emulator.
@azure/cosmos npm package version is 3.0.4

**Comment by southpolesteve** [comment]
@arulselvam Thanks for the bug report. I'll investigate this but as a workaround try putting this at the top of your entry point file: `process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;`

**Comment by southpolesteve** [comment]
I'm going to remove this option as it doesn't currently work. There are now two ways to do this:

1. Pass a custom agent

``` js
    const client = new CosmosClient({
      endpoint,
      key,
      agent: new https.Agent({
        rejectUnauthorized: false
      })
    });
```

2. Globally disable SSL Checks:

``` js
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
    const client = new CosmosClient({
      endpoint,
      key
    });
```
