### ISSUE TITLE
Additional context/debug information for required retry attempts

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/azure-cosmos-js#392]
Is there a way to see how many iterations were needed to successfully complete an operation, or what restriction led to its termination? Some debug log information might be helpful here. Also, whether the `maxRetryAttemptCount` or` maxWaitTimeInSeconds` led to the error being bubbled up.

**Comment by southpolesteve** [comment]
We've got some existing WIP code that will help address this. Stay tuned.
