### ISSUE TITLE
Thrown errors in StoredProcedures not reflected in Client

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/azure-cosmos-js#393]
Currently if an `Error` is thrown inside a  CosmosDB Stored Procedure, this will not be reflected in the Client SDK.

```javascript
function sproc() {
  throw new Error('Ups')
}
```

```javascript
try {
  const resp = await container.scripts.storedProcedure('getPendingJobs').execute(undefined, [], { enableScriptLogging: true })
} catch(err) {
  console.log(err) // I would expect, that CosmosDB return some kind of error information which should be handled by the client and propagated as an JS error again
}
```

The result is that currently the "resource" property of the response object will be initialized with an empty string value. Therefore one is be forced to catch exceptions in the Stored Procedure in order to put the error information explicitly inside the response object. A developer then has to check the resource property accordingly to handle errors inside SPs.

```javascript
function sproc() {
  try {
   throw new Error('Ups')
  } catch(err) {
     getContext().getResponse().setBody({err: err.toString()})
  }
}
```

```javascript
const resp = await container.scripts.storedProcedure('sproc').execute(undefined, [], { enableScriptLogging: true })
if(resp.resource.err) {
  console.log(err)
} else {
  ...
}
```

IMHO this is not a good approach to handle errors.

Maybe there is a best practice or pattern how errors in Stored Procedures should be handled inside Clients. But i didn't found any examples here.

**Comment by southpolesteve** [comment]
I agree we could handle this better on the SDK side. Throwing by default would be a breaking change though. We could add an option to opt-in to the behavior. I'll discuss with the team and circle back.

**Comment by southpolesteve** [comment]
@jrauschenbusch I'm not able to repro the scenario above. Are you not seeing an error when the sproc throws? I get a thrown error with an embedded message. I think we could surface that much better, but it does appear to throw. 

Here is the code I am using:

```
// @ts-check
const { CosmosClient } = require('@azure/cosmos')

const endpoint = 'REPLACE'
const key = 'REPLACE'

const client = new CosmosClient({
  endpoint,
  key
})

function sproc() {
  throw new Error('Ups')
}

async function main() {
  try {
    const resp = await client
      .database('demo')
      .container('events')
      .scripts.storedProcedure('sproc')
      .execute(undefined, [], { enableScriptLogging: true })
  } catch (err) {
    console.log(
      JSON.parse(
        err.body.message
          .split(', ')[0]
          .split('\r\n')[0]
          .split(': ')
      )
    )
  }
}

main()
```
