### ISSUE TITLE
Sample: Using continuation tokens with stored procs

### ISSUE THREAD

**Issue by deborahc** [Azure/azure-cosmos-js#401]
Ref: https://github.com/MicrosoftDocs/azure-docs/issues/36436

User would like a sample on how to write a stored proc that updates multiple documents, and how to use continuation token to handle long running stored procs.

**Comment by southpolesteve** [comment]
Available at https://github.com/Azure/azure-cosmos-js/blob/master/samples/BulkUpdateWithSproc.ts
