### ISSUE TITLE
Backport Retry on EPIPE error to v2

### ISSUE THREAD

**Issue by joecohens** [Azure/azure-cosmos-js#404]
https://github.com/Azure/azure-cosmos-js/issues/399
https://github.com/Azure/azure-cosmos-js/pull/400

**Comment by christopheranderson** [comment]
This is kind of a gray area. It wasn't really a bug we didn't retry on EPIPE, but it's not really a feature.

We normally only backport bug fixes to previous versions.

@stfaul - tie breaking vote?
