### ISSUE TITLE
Unexpected requestTimeout behavior

### ISSUE THREAD

**Issue by henryjw** [Azure/azure-cosmos-js#407]
For some reason, if I set `requestTimeout` to either `undefined` or a value small enough that it should trigger the error, my query takes 20-22 seconds before finally timing out. Is this expected behavior? Below is the code I'm trying to execute (works fine if timeout isn't set).

Version: 3.1.1

**Code**
```javascript
constructor(connectionConfig, description = "Cosmos DB") {
    super(connectionConfig, description, PLUGIN_NAME);

    this._cosmosClient = new CosmosClient({
        endpoint: this.connectionConfig.url,
        key: this.connectionConfig.key,
        connectionPolicy: {
            requestTimeout: 100,
        },
    });
}

async _checkHealth() {
    try {
        await this._cosmosClient.databases.query("SELECT 1").fetchNext();

        return {
            status: "healthy",
        };
    } catch (err) {
        return {
            status: "unhealthy",
            error: err,
        };
    }
}
```

**Error returned after 20+ seconds**
```json
 {
    "code": "TimeoutError",
    "name": "TimeoutError",
    "headers": {
        "x-ms-throttle-retry-count": 0,
        "x-ms-throttle-retry-wait-time-ms": 0
    }
}
```

**Comment by christopheranderson** [comment]
requestTimeout is a means to control network level issues, not a way of timing out queries

It's also measured in milliseconds, so what's happening in your case it that after 100ms the request is being cancelled. For a query, it's fairly easy to run longer than 100ms, thus the timeout exception.

To control the timeout on the query, we're planning on adding AbortController support.

I'm going to resolve both your questions with this new issue I created to track this: https://github.com/Azure/azure-cosmos-js/issues/410

**Comment by henryjw** [comment]
Right. My idea was to use the `requestTimeout` as a "connection timeout" rather than a "query timeout". However, that fails when the connection takes longer to establish than the request timeout. For instance, if I set the timeout to something ridiculously low like 1ms (or even 100ms as in my example), then the SDK won't return the timeout error until 20+ seconds.

**Comment by southpolesteve** [comment]
@henryjw this is by design. `requestTimeout` setting is below our retry logic in the SDK internals. The  SDK is retrying after each timeout is hit https://github.com/Azure/azure-cosmos-js/blob/abort-query/src/retry/defaultRetryPolicy.ts#L128-L129
