### ISSUE TITLE
Is there a way to set a query timeout?

### ISSUE THREAD

**Issue by henryjw** [Azure/azure-cosmos-js#408]
Maybe I'm not reading the docs correctly, but I haven't been able to find a way to set a query timeout. I was able to find a way to set a request timeout, but it's not exactly what I'm looking for.

Below is an idea of what I imagine such configuration would look like

**Example**

```javascript
// Should throw Timeout error if query takes longer than 300ms
const results = await cosmosClient.databases
    .query(potentiallySlowQuery, { queryTimeout: 300 })
    .fetchAll();
```

**Comment by christopheranderson** [comment]
We need to add support for cancelling queries to the SDK still. Doesn't currently exist. Created this issue to track: https://github.com/Azure/azure-cosmos-js/issues/410

**Comment by southpolesteve** [comment]
@henryjw I added a test showing how to do this using AbortController https://github.com/Azure/azure-cosmos-js/pull/413

**Comment by southpolesteve** [comment]
Azure has an abort controller library that makes this very trivial. You can pass AbortController.timeout(300) https://www.npmjs.com/package/@azure/abort-controller

**Comment by henryjw** [comment]
@southpolesteve Thanks! `AbortController.timeout()` is exactly what I was looking for.
Also, I'm not sure why, but when instantiate a new controller like in the test, I get `signal` as undefined.
