### ISSUE TITLE
Singular methods to instantiate reference objects

### ISSUE THREAD

**Issue by southpolesteve** [Azure/azure-cosmos-js#41]
Coming out of #39 we decided to move go with approach 5. `get` methods will become singular methods one level up the object hierarchy: 

``` js
// Current
client.databases.get(id)
client.databases.get(id).containers.get(id)
client.databases.get(id).containers.get(id).items.get(id)

// New
client.database(id)
client.database(id).container(id)
client.database(id).container(id).item(id)
```

**Comment by christopheranderson** [comment]
Are you putting `.database` only on the common parent, or also under the plural?

Can I do both of these or just the first one?
```typescript
client.database(id)
client.databases.database(id)
```

**Comment by southpolesteve** [comment]
My thought was only on the common parent for now. Not opposed to having it both places, but would like to try Proxy for that first.

**Comment by christopheranderson** [comment]
@southpolesteve - this is done now? https://github.com/Azure/azure-cosmos-js/pull/43

**Comment by southpolesteve** [comment]
Yes
