### ISSUE TITLE
Support AbortSignal on query operations

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmos-js#410]
## Problem

You cannot cancel long queries.

## Proposed solution

Support AbortSignal on relevant query operations (fetchNext/fetchAll).

Another alternative is adding AbortSignal to FeedOptions (which would allow support for AsyncIterable). This feels a bit weird for things like fetchNext/fetchAll since you usually pass AbortSignal on the method you're awaiting.

@stfaul - thoughts?

**Comment by southpolesteve** [comment]
This is already supported. Added a test here https://github.com/Azure/azure-cosmos-js/pull/413
