### ISSUE TITLE
Need samples on how to use SDK with Partitioned Containers

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmos-js#81]
The way you make calls to paritioned containers vs non-partitioned containers is fairly different, and we should have more samples/docs/typedoc examples which show how this works. The way the SDK works today will lead most folks to using non-partitioned containers.

**Comment by PrimeObjects** [comment]
When I used await container.item(id).read(); I got error "The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection", 

then I changed to await container.item(id).read({partitionKey:[]}), it only returns document that has no value in organizationId field.
 
I do have a particialKey which is /organizationId
When I use await container.item(id).read({partitionKey:'/organizationId'}); it always say Not Found.

Please help!
Thanks lot!
Gary

**Comment by barryajones** [comment]
@PrimeObjects If your partition key is **organizationId** then you should pass it to the read method like so:

```javascript
await container.item(id).read({partitionKey:['/organizationId']});
```

**Comment by mybouhssina** [comment]
@barryajones do you mean that we have to pass the value or the path of the paritionKey ? 
what if we don't want to pass the partition key and find only by id ?

**Comment by christopheranderson** [comment]
Covered by NP->P changes. All samples will be partitioned. (Any semi-off topic conversations should move to new issues).
